//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public Action()
        {
            this.SysPage = new HashSet<SysPage>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> ActionCategoryId { get; set; }
        public string Url { get; set; }
        public bool IsShowMenu { get; set; }
    
        public virtual ActionCategory ActionCategory { get; set; }
        public virtual ICollection<SysPage> SysPage { get; set; }
    }
}
