//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartofAccount
    {
        public ChartofAccount()
        {
            this.VoucherDetail = new HashSet<VoucherDetail>();
        }
    
        public string Id { get; set; }
        public string Code { get; set; }
        public string AccountName { get; set; }
        public Nullable<long> AccountLevel { get; set; }
        public long ParentId { get; set; }
        public string DrCr { get; set; }
        public bool IsActive { get; set; }
        public bool IsContinue { get; set; }
        public int CompanyId { get; set; }
        public bool IsAdd { get; set; }
        public bool IsUpdate { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual ICollection<VoucherDetail> VoucherDetail { get; set; }
    }
}
