//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public long Id { get; set; }
        public long InvoiceId { get; set; }
        public int ProductId { get; set; }
        public double Rate { get; set; }
        public int Qty { get; set; }
        public double Amount { get; set; }
        public System.DateTime ReportDate { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
