//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string Mr { get; set; }
        public string Prefix { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string Cnic { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> RefLocationId { get; set; }
        public string RefName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
