//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.SysPage = new HashSet<SysPage>();
        }
    
        public long Id { get; set; }
        public string PermName { get; set; }
    
        public virtual ICollection<SysPage> SysPage { get; set; }
    }
}
