//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
        public long Id { get; set; }
        public long RoleId { get; set; }
        public long PermId { get; set; }
        public long ActionId { get; set; }
        public bool IsAllowed { get; set; }
    }
}
