//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysPage
    {
        public long Id { get; set; }
        public string PageName { get; set; }
        public Nullable<long> ActionId { get; set; }
        public Nullable<long> ParmissionId { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
