//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public Voucher()
        {
            this.VoucherDetail = new HashSet<VoucherDetail>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public double Amount { get; set; }
        public string Type { get; set; }
        public bool IsActive { get; set; }
        public bool IsContinue { get; set; }
        public long CompanyId { get; set; }
        public long LabId { get; set; }
        public bool IsAdd { get; set; }
        public bool IsUpdate { get; set; }
        public bool IsDelete { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Lab Lab { get; set; }
        public virtual ICollection<VoucherDetail> VoucherDetail { get; set; }
    }
}
